### ISSUE TITLE
Using FAB in project

### ISSUE THREAD

**Issue by owuor91** [fabionuno/FloatingActionButton-Xamarin.Android#1]
Hi Fabio,
Is there a way I can use this already bound library in my xamarin project or do I have to bind it again on my own? copying the FAB.Bind-Xamarin.Android folder to my project seems to have no effect.

**Comment by fabionuno** [comment]
Hi @owuor91 
There is a Nuget package with this FAB. https://www.nuget.org/packages/FAB.XamarinAndroid/
Adding this package in your project is the easy way to use this FAB version and stay updated with new releases.

**Comment by owuor91** [comment]
Thanks a million
