### ISSUE TITLE
How to change the Normal Color and Pressed Color Values programmatically?

### ISSUE THREAD

**Issue by fahadrehman** [fabionuno/FloatingActionButton-Xamarin.Android#10]
How to change the NormalColor and PressedColor Values programmatically?

I dont want to take the Color From Resources like
actionButtonMenu.SetMenuButtonColorRippleResId(Resource.Color.background_dark);

 i want to apply these colors from Color  property

**Comment by fahadrehman** [comment]
Any body Please Help me or tell me any work around to do this?

**Comment by fabionuno** [comment]
Hi @fahadrehman  you can use the `MenuButtonColorNormal` and `MenuButtonColorPressed` properties.

```cs
actionButtonMenu.MenuButtonColorNormal = Android.Graphics.Color.Green;
actionButtonMenu.MenuButtonColorPressed = Android.Graphics.Color.YellowGreen;
```

**Comment by fahadrehman** [comment]
Thanks it worked.
