### ISSUE TITLE
How to change color of menu_labels_colorNormal by programmatically 

### ISSUE THREAD

**Issue by sujeetulli** [fabionuno/FloatingActionButton-Xamarin.Android#5]
Hi,

Is their any method for changing the color of below list.
menu_labels_colorNormal
menu_labels_colorPressed
menu_labels_colorRipple
menu_labels_textColor

Please let me know any solution for this...

**Comment by fabionuno** [comment]
Update to version 1.6.3 and use SetLabelColors and SetLabelTextColor to change Label's background and text colors programmatically
