### ISSUE TITLE
How to add a Floating Action Menu in my Main Activity?

### ISSUE THREAD

**Issue by joanlopez** [fabionuno/FloatingActionButton-Xamarin.Android#7]
Hi,

I have the following layout:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#E2E2E2"
    android:id="@+id/sampleMainLayout">
    <FrameLayout
        android:id="@+id/sampleContentFragment"
        android:layout_weight="2"
        android:layout_width="match_parent"
        android:layout_height="0px" />
</LinearLayout>
```

This FrameLayout is filled (programatically) with a Fragment that has three TabViews (ViewPager with PageAdapter). 

Something like the main screen of WhatsApp:

![image](https://cloud.githubusercontent.com/assets/5459617/17071870/9201255a-5064-11e6-82e8-2cba9359f8d4.png)

Now I want to add a Floating Action Menu on the bottom right corner that will contain three Floating Action Buttons (appart from the main button (menú). Similar to your "_red_menu"_ example.

The problem is that when I've added a Floating Action Menu (almost exactly as your "_red_menu_" example), it appears and works correctly, but other things disappears.

How I have to add & configure the Floating Action Menu to maintain my main layout with the TabViews and with the Floating Action Menu overlayed?

I don't know why the other things disappears. It seems that the menu is occopying all the screen, which I think that is right, but I think that when the menu is disabled (not showing the buttons), my other things should be visible, but not.

Of course, I've tried changing the `android:background` attribute but everything remains equals.

Thanks a lot,

Joan

**Comment by fabionuno** [comment]
Hi @joanlopez  sorry for the delayed response.
I believe you already have found the solution to this problem, anyway I added an example of FloatingActionMenu working inside a Fragment with ViewPager and TabLayout.
